"""Initial migration

Revision ID: 9c5fa2ce33fe
Revises: 
Create Date: 2025-02-27 13:37:16.935358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c5fa2ce33fe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('channels', sa.Integer(), nullable=False),
    sa.Column('bands', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_metadata_id'), 'image_metadata', ['id'], unique=False)
    op.create_table('kmeans_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('img_bytes', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['image_metadata.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kmeans_results_id'), 'kmeans_results', ['id'], unique=False)
    op.create_table('pca_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('img_bytes', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['image_metadata.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pca_results_id'), 'pca_results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pca_results_id'), table_name='pca_results')
    op.drop_table('pca_results')
    op.drop_index(op.f('ix_kmeans_results_id'), table_name='kmeans_results')
    op.drop_table('kmeans_results')
    op.drop_index(op.f('ix_image_metadata_id'), table_name='image_metadata')
    op.drop_table('image_metadata')
    # ### end Alembic commands ###
